services:
  api-server:
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    environment:
      DASS_LOG_LEVEL: DEBUG

  scheduler:
    command: python -m app.cli scheduler
    volumes:
      - ./backend:/app
    environment:
      DASS_LOG_LEVEL: DEBUG

  worker:
    command: python -m app.cli worker
    volumes:
      - ./backend:/app
    environment:
      DASS_LOG_LEVEL: DEBUG

